### ISSUE TITLE
Bug: /spotify/current causing an error sometimes

### ISSUE THREAD

**Issue by Le0X8** [Le0X8/additional-readme-stats#1]
/spotify/current returns the following HTML code instead of the SVG:

```html
<br />
<b>Fatal error</b>:  Uncaught mysqli_sql_exception: Duplicate entry 'ji431f2ja6vyczqq0eatna6jb' for key 'PRIMARY' in /www/htdocs/w01c082e/armstats.leox.dev/src/apis/spotify/recents/recents.php:244
Stack trace:
#0 /www/htdocs/w01c082e/armstats.leox.dev/src/apis/spotify/recents/recents.php(244): mysqli_query(Object(mysqli), 'INSERT INTO spo...')
#1 /www/htdocs/w01c082e/armstats.leox.dev/src/apis/spotify/current/current.php(29): include('/www/htdocs/w01...')
#2 /www/htdocs/w01c082e/armstats.leox.dev/src/apis/spotify/spotify.php(350): include('/www/htdocs/w01...')
#3 /www/htdocs/w01c082e/armstats.leox.dev/index.php(55): include('/www/htdocs/w01...')
#4 {main}
  thrown in <b>/www/htdocs/w01c082e/armstats.leox.dev/src/apis/spotify/recents/recents.php</b> on line <b>244</b><br />

```

The ./html endpoint works fine for some reason though

**Comment by Le0X8** [comment]
Shouldn't be a problem anymore.
